FROM node:14.16.0-alpine3.13 AS build-stage

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
ENV REACT_APP_API_URL=http://147.182.253.161:3001/api
RUN npm run build

FROM nginx:1.12-alpine 
COPY --from=build-stage /app/build /usr/share/nginx/html
EXPOSE 80
ENTRYPOINT [ "nginx", "-g", "daemon off;" ] 